theme: jekyll-theme-minimal
title: CallPro Documentation
email: j.bennink@calway.nl
description: > # this means to ignore newlines until "baseurl:"
  CallPro Documentatie, Handleidingen, Release Notes, Tips and Tricks
twitter_username: calwayNL
github_username:  calway